spring.application.name=ShopEasy

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/shopeasy?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Raham@404
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=ShopEasySecretKey123456789012345678901234567890
jwt.expiration=86400000 